<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'username' => 'john_doe',
                'email' => 'john.doe@example.com',
                'display_name' => 'John Doe',
                'birthday' => '1990-05-15',
                'age' => 34,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'jane_smith',
                'email' => 'jane.smith@example.com',
                'display_name' => 'Jane Smith',
                'birthday' => '1985-10-22',
                'age' => 39,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'mark_twain',
                'email' => 'mark.twain@example.com',
                'display_name' => 'Mark Twain',
                'birthday' => '1995-04-10',
                'age' => 29,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'lucy_heartfilia',
                'email' => 'lucy.heartfilia@example.com',
                'display_name' => 'Lucy Heartfilia',
                'birthday' => '1998-07-20',
                'age' => 26,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'edward_elric',
                'email' => 'edward.elric@example.com',
                'display_name' => 'Edward Elric',
                'birthday' => '2000-12-03',
                'age' => 24,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'emma_watson',
                'email' => 'emma.watson@example.com',
                'display_name' => 'Emma Watson',
                'birthday' => '1994-02-15',
                'age' => 30,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'leo_messi',
                'email' => 'leo.messi@example.com',
                'display_name' => 'Leo Messi',
                'birthday' => '1987-06-24',
                'age' => 37,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'sakura_haruno',
                'email' => 'sakura.haruno@example.com',
                'display_name' => 'Sakura Haruno',
                'birthday' => '2001-03-28',
                'age' => 23,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'bruce_wayne',
                'email' => 'bruce.wayne@example.com',
                'display_name' => 'Bruce Wayne',
                'birthday' => '1981-09-17',
                'age' => 43,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'natasha_romanoff',
                'email' => 'natasha.romanoff@example.com',
                'display_name' => 'Natasha Romanoff',
                'birthday' => '1984-11-22',
                'age' => 40,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'is_admin' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'jonathan_strauss',
                'email' => 'j.strauss@example.com',
                'display_name' => 'Nathan',
                'birthday' => '1988-03-22',
                'age' => 35,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'mike_jones',
                'email' => 'mike.jones@example.com',
                'display_name' => 'Mike Jones',
                'birthday' => '1992-07-10',
                'age' => 31,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'sara_connor',
                'email' => 'sara.connor@example.com',
                'display_name' => 'Sara Connor',
                'birthday' => '1985-11-05',
                'age' => 37,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'david_brown',
                'email' => 'david.brown@example.com',
                'display_name' => 'David Brown',
                'birthday' => '1995-01-20',
                'age' => 28,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'lisa_white',
                'email' => 'lisa.white@example.com',
                'display_name' => 'Lisa White',
                'birthday' => '1993-09-15',
                'age' => 30,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'chris_green',
                'email' => 'chris.green@example.com',
                'display_name' => 'Chris Green',
                'birthday' => '1987-12-30',
                'age' => 35,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'emily_johnson',
                'email' => 'emily.johnson@example.com',
                'display_name' => 'Emily Johnson',
                'birthday' => '1991-04-25',
                'age' => 32,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'robert_miller',
                'email' => 'robert.miller@example.com',
                'display_name' => 'Robert Miller',
                'birthday' => '1989-08-14',
                'age' => 34,
                'gender' => 'male',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'laura_davis',
                'email' => 'laura.davis@example.com',
                'display_name' => 'Laura Davis',
                'birthday' => '1994-06-18',
                'age' => 29,
                'gender' => 'female',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}